// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xocbdwmlibgfbuqhdolv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvY2Jkd21saWJnZmJ1cWhkb2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTcxMjYsImV4cCI6MjA2Nzg3MzEyNn0.lPO6DWXlNfjOACxxZMitq0-yX26yyM-Hfo9a21hvqrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});